// Exam question banks transcribed verbatim from the LSAG reference
// (_ref/lsag/lsag-ref/exam-page-reference.tsx). Each question keeps the source
// wording. Format: { q: prompt, o: options, a: index of the correct option }.

export interface SeedExamQuestion {
  q: string;
  o: string[];
  a: number;
}

export interface SeedExam {
  title: string;
  description: string;
  questions: SeedExamQuestion[];
}

export const EXAM_SEED: SeedExam[] = [
  {
    title: "Examen Mixto SADJ - Convocatoria I",
    description: "Banco oficial de preguntas — Convocatoria I.",
    questions: [
      { q: "Al redactar la Fundamentacion de los Cargos con varios acusados, que orden debe seguirse?", o: ["Empezar por el acusado con menor cantidad de cargos para ir aumentando", "Listar los cargos en orden alfabetico por nombre del acusado", "Comenzar por el acusado de mayor rango o relevancia social", "Empezar por los cargos compartidos por mayor numero de acusados y terminar por los individuales"], a: 3 },
      { q: "Para que sirve el Aviso Legal dentro de la estructura de una acusacion?", o: ["Para notificar al acusado de sus derechos constitucionales", "Para informar al juez de la fecha del juicio", "Para prevenir la publicacion, difusion y copia del documento a partes no implicadas o no autorizadas", "Para registrar la firma del Fiscal General en el expediente"], a: 2 },
      { q: "Cuanto tiempo quedan registradas las sanciones moderadas?", o: ["1 mes", "6 meses", "2 meses", "3 meses"], a: 3 },
      { q: "Cuando puede el fiscal realizar una intervencion activa dentro de la estacion?", o: ["Siempre que considere que hay un error procedimental grave", "Unicamente a solicitud del oficial actuante", "De oficio, cuando detecte una vulneracion de derechos fundamentales", "Cuando el detenido lo solicite expresamente al fiscal presente"], a: 1 },
      { q: "Cuantos niveles tienen las sanciones OOC segun la Normativa?", o: ["Cinco", "Dos", "Cuatro", "Tres"], a: 3 },
      { q: "En que consiste la Negociacion de Culpabilidad segun el Manual?", o: ["Un proceso en el que el juez propone una pena reducida al fiscal para agilizar el juicio", "Un acuerdo entre la defensa y el jurado para evitar el veredicto publico", "Un pacto en el que la fiscalia propone a la defensa restar tiempo de condena o rebajar delitos a cambio de que el acusado acepte su culpabilidad", "La retirada formal de todos los cargos por parte de la fiscalia antes del juicio"], a: 2 },
      { q: "A quienes va dirigida la orientacion juridica del programa segun su definicion?", o: ["Exclusivamente a los fiscales de menor rango en practicas", "A agentes policiales y ciudadanos que se encuentren en una estacion de policia, unicamente cuando dicha orientacion sea solicitada", "A los jueces y magistrados de la Corte de Los Santos", "Al personal de direccion y mando de las agencias gubernamentales"], a: 1 },
      { q: "Donde deben estar los miembros que no se encuentren de servicio dentro de TeamSpeak?", o: ["En cualquier canal disponible libremente", "En el canal de su rango correspondiente", "En la categoria de canales 'Out of Character / AFK'", "En el canal de espera general del SADJ"], a: 2 },
      { q: "Que beneficio obtienen los civiles gracias al programa segun el documento?", o: ["Acceso directo a la defensa publica a traves del fiscal presente en la estacion", "La posibilidad de solicitar la anulacion de la detencion si el fiscal lo considera procedente", "Mayores garantias de respeto de sus derechos fundamentales y orientacion legal basica durante el procedimiento", "La exencion de cargos leves si el fiscal certifica un procedimiento correcto"], a: 2 },
      { q: "Que principio rige la obligatoriedad de esta Normativa para todos los miembros?", o: ["Solo es obligatoria para miembros con rango de Prosecutor o superior", "Es opcional hasta que el miembro supere el periodo de prueba", "Es de cumplimiento obligatorio para todos, y cualquier violacion puede resultar en sanciones incluyendo la expulsion", "Solo aplica durante los turnos activos dentro del juego"], a: 2 },
      { q: "Cual de los siguientes actos conlleva directamente la sancion de expulsion?", o: ["Mal uso de las unidades de la agencia", "Ausencia injustificada por dos semanas", "Falsificacion de pruebas", "No conectarse a la radio en turno"], a: 2 },
      { q: "Que debe hacer el fiscal al finalizar su turno en la estacion?", o: ["Presentar un informe de cargos provisional ante la Corte de Los Santos", "Notificar al USMS sobre cualquier incidente observado durante el turno", "Redactar un registro interno con observaciones generales y sugerencias de mejora relacionadas con la legalidad de los procedimientos", "Elevar un informe disciplinario sobre los agentes con faltas detectadas"], a: 2 },
      { q: "Que sucede tras finalizar el Alegato Final si el veredicto no esta claro para el juez?", o: ["Se repite el juicio desde la fase de investigacion", "El jurado emite su veredicto de forma automatica sin mas deliberacion", "Se procede a un receso con o sin medidas cautelares para finalmente determinar un fallo", "La fiscalia tiene la ultima palabra y dicta la sentencia provisional"], a: 2 },
      { q: "Que significa el principio 'In dubio pro reo'?", o: ["Nadie puede ser juzgado dos veces por el mismo hecho", "Si existe duda razonable sobre la culpabilidad del acusado, este debe ser absuelto", "Ninguna pena puede aplicarse sin ley previa que la defina", "Nadie puede ser privado de su libertad sin causa legal justificada"], a: 1 },
      { q: "Cual de las siguientes es una conducta catalogada como sancion moderada?", o: ["Actos de corrupcion o soborno", "Uso no autorizado de equipamiento oficial", "Participacion con el crimen organizado", "Ausencia injustificada de mas de un mes"], a: 1 },
      { q: "En que consiste un juicio civil segun el Manual?", o: ["En un proceso donde el Estado acusa a un ciudadano por violar leyes federales", "En una disputa privada entre personas o empresas resuelta por compensaciones economicas o medidas de equidad, sin intervencion de la fiscalia salvo excepciones", "En un juicio donde se juzgan violaciones directas a derechos constitucionales", "En un proceso exclusivo para funcionarios publicos imputados por corrupcion"], a: 1 },
      { q: "Que ocurre en la fase de Comparecencia Inicial segun el Manual?", o: ["La fiscalia presenta su escrito de acusacion formal ante la corte por primera vez", "Se realiza la lectura de los cargos, el acusado declara su posicion y se pactan medidas provisionales o fianza", "La defensa entrega sus pruebas y testigos a la fiscalia de forma obligatoria", "El juez dicta sentencia provisional en funcion de las pruebas ya disponibles"], a: 1 },
      { q: "Que tipo de formacion reciben constantemente los fiscales segun el Manual de Procedimientos?", o: ["Solo simulaciones de juicios y oratoria", "Leyes y su aplicacion, simulaciones de juicios, oratoria, analisis de evidencias, tecnicas de interrogatorio y coordinacion interdepartamental", "Unicamente tecnicas de interrogatorio y coordinacion con la policia", "Cursos de vestimenta y protocolo institucional"], a: 1 },
      { q: "Que conducta se clasifica especificamente como sancion grave?", o: ["Retraso menor en la entrega de informes", "Fumar en las oficinas de la agencia", "Filtrar informacion", "Mal uso de las unidades de la agencia"], a: 2 },
      { q: "Con que agencia se contacta cuando se requiere asistencia o proteccion inminente ante una amenaza a un empleado del SADJ?", o: ["FIB", "LSPD", "USSS", "USMS"], a: 3 }
    ]
  },
  {
    title: "Examen Mixto SADJ - Convocatoria II",
    description: "Banco oficial de preguntas — Convocatoria II.",
    questions: [
      { q: "En el sistema GPS de vehiculos oficiales, que indica la baliza de color Azul?", o: ["Vehiculo en estado de emergencia requiriendo apoyo", "Vehiculo inoperativo o estatico", "Vehiculo operativo realizando labores basicas y ordinarias", "Vehiculo respondiendo a un allanamiento o un operativo especial"], a: 2 },
      { q: "Cuantos empleados rotan en el Centro de Comunicaciones del Departamento de Justicia?", o: ["3", "7", "10", "5"], a: 3 },
      { q: "Cuando se activa la baliza Roja en un vehiculo del SADJ?", o: ["Cuando el vehiculo esta realizando labores rutinarias de oficina", "Cuando el vehiculo acude a un allanamiento o un operativo especial", "En caso de agresion, secuestro o accidente requiriendo apoyo", "Cuando el vehiculo se encuentra estatico en el aparcamiento del HQ"], a: 2 },
      { q: "Con que rango ingresa un candidato aceptado tras superar el proceso de seleccion?", o: ["Prosecutor", "District Attorney", "Functionary", "Assistant Prosecutor"], a: 2 },
      { q: "Cual es la labor clave y principal de SADJ segun el Manual de Procedimientos?", o: ["Supervisar allanamientos policiales", "Gestionar el programa de proteccion de testigos", "Enjuiciar la mayor cantidad de casos posibles", "Coordinar entrenamientos interdepartamentales"], a: 2 },
      { q: "Que obligacion tiene la Fiscalia durante la fase de Intercambio de Pruebas?", o: ["Ocultar las pruebas mas comprometedoras hasta el dia del juicio", "Proporcionar a la defensa todas las pruebas de las que disponga para que pueda formalizar su defensa", "Solicitar al juez la exclusion de las pruebas de la defensa antes del juicio", "Entregar unicamente las pruebas que no sean de caracter federal"], a: 1 },
      { q: "Que ocurre cuando un funcionario acumula tres (3) sanciones leves?", o: ["Es expulsado directamente", "Se convierte automaticamente en una sancion grave", "Se convierte en una sancion moderada", "Recibe una suspension de 7 dias"], a: 2 },
      { q: "En que situaciones se utiliza el APX 7000 Compacto de Motorola segun el Manual?", o: ["Exclusivamente en los vehiculos de patrulla marcados", "En operativos o situaciones complejas fuera del vehiculo, donde se necesita gran alcance para Mutual-AID o dispositivos amplios", "Solo dentro de las oficinas del SADJ como equipo de respaldo", "Unicamente en juicios celebrados fuera de Los Santos"], a: 1 },
      { q: "En el procedimiento de revision de telefono movil, bajo que condicion se autoriza en flagrancia sin orden judicial?", o: ["Cuando el detenido lo consiente voluntariamente", "Cuando el fiscal lo considere conveniente", "Cuando el detenido cometo en flagrancia delitos graves o federales y el procedimiento fue correcto", "Siempre que exista cualquier tipo de delito previo"], a: 2 },
      { q: "Cuando se detecta una baliza Roja y no se recibe feedback de la unidad, a que agencia se contacta?", o: ["Al FIB CIRG", "Al LSPD BCC", "Al USMS CC", "Al SAES SCU"], a: 2 },
      { q: "Cual es la actitud inicial del fiscal al presentarse en una estacion bajo el programa?", o: ["Interviene directamente para corregir cualquier error procedimental que detecte", "Solicita inmediatamente el expediente del detenido para revision", "Mantiene una observacion pasiva del procedimiento, sin interferir ni interrumpir las actuaciones en curso", "Convoca a los agentes a una reunion de coordinacion legal antes de actuar"], a: 2 },
      { q: "Que funcion tiene el Jurado en aquellos juicios donde esta presente?", o: ["Decidir las cuestiones de derecho aplicables al caso", "Proponer la condena o la absolucion al Juez en forma de recomendacion escrita", "Determinar los hechos a partir de las evidencias presentadas", "Supervisar el comportamiento del fiscal durante el juicio"], a: 2 },
      { q: "Que protege el principio 'Non reformatio in peius'?", o: ["El derecho del acusado a que se le asigne un abogado de oficio", "El derecho a recurrir una sentencia sin temor a que la pena sea empeorada como resultado del recurso", "La garantia de que las pruebas obtenidas ilegalmente sean excluidas del proceso", "La obligacion de la fiscalia de revelar todas sus pruebas a la defensa"], a: 1 },
      { q: "Para que se permite exclusivamente el uso de los comandos '!!' o '/b'?", o: ["Para comunicar ordenes operativas urgentes", "Para reportar infracciones de companeros", "Para aclaraciones de rol", "Para solicitar permisos a superiores"], a: 2 },
      { q: "Segun la Normativa, que requisito de ingreso se exige ademas del nivel de cuenta minimo?", o: ["Tener al menos 6 meses de experiencia en roleplay", "No tener sanciones graves", "Haber completado la formacion fiscal inicial", "Contar con la recomendacion de un miembro activo"], a: 1 },
      { q: "Cuantos tipos de juicios principales recoge el Manual de Acusacion y Juicios?", o: ["Cinco", "Dos", "Cuatro", "Tres (Penales, Civiles y Constitucionales)"], a: 3 },
      { q: "En el procedimiento de levantamiento de cadaver, a quien debe ser entregado el cadaver para su levantamiento forense?", o: ["Al FIB para su analisis federal", "Al USMS para custodia judicial", "A SAES para su levantamiento forense", "Al equipo de Asuntos Internos de SADJ"], a: 2 },
      { q: "Durante el Alegato Inicial, que esta permitido hacer?", o: ["Presentar objeciones contra los argumentos de la parte contraria", "Interrogar a los testigos de forma preliminar", "Exponer el caso y los delitos que se busca imputar, sin que esten permitidas las objeciones", "Presentar todas las pruebas documentales disponibles"], a: 2 },
      { q: "Quien puede colocar una sancion grave segun el Marco Sancionatorio?", o: ["Cualquier fiscal senior sin restricciones", "El Attorney General o el Assistant Attorney General", "El District Attorney con aprobacion del Prosecutor", "Solo el Liderazgo de la organizacion"], a: 1 },
      { q: "Puede el fiscal del programa negociar directamente con los detenidos?", o: ["Si, en el marco de una posible negociacion de culpabilidad anticipada", "Solo si cuenta con autorizacion escrita del Fiscal de Distrito", "No, el fiscal no participa en interrogatorios ni negocia con detenidos bajo ninguna circunstancia dentro del programa", "Si, exclusivamente en casos de detenidos con delitos leves"], a: 2 }
    ]
  },
  {
    title: "Examen Mixto SADJ - Convocatoria III",
    description: "Banco oficial de preguntas — Convocatoria III.",
    questions: [
      { q: "Que puede ocurrir si se abusa incorrectamente del simplex de asignacion segun el Manual?", o: ["Se pierde acceso a los canales interdepartamentales de forma automatica", "Se notifica al Fiscal General para revision disciplinaria inmediata", "Puede conllevar sanciones", "Se suspende el equipo de comunicacion del empleado hasta nueva orden"], a: 2 },
      { q: "Donde se ubica fisicamente el Centro de Comunicaciones del SADJ?", o: ["En la sede de Paleto Bay", "En el Tribunal de Los Santos", "En el Departament of Justice HeadQuarters en Los Santos", "En la oficina del Fiscal de Blaine County"], a: 2 },
      { q: "Que significan las siglas LSES segun la tabla de abreviaturas del Manual?", o: ["Los Santos Emergency Squad", "Law Services and Emergency System", "Los Santos Emergency Services", "Legal and Safety Emergency Section"], a: 2 },
      { q: "Que es la acusacion segun el Manual de Acusacion y Juicios?", o: ["Un informe policial que detalla los hechos ocurridos durante una detencion", "El acto procesal mediante el cual la abogacia del estado solicita la imputacion y condena de la parte acusada, presentando hechos, calificacion juridica y pruebas", "Una notificacion informal al acusado de los cargos que se le imputan", "Un documento interno exclusivo de la Fiscalia sin efecto ante la corte"], a: 1 },
      { q: "Que aporta el programa a las agencias policiales en materia de tipificacion de delitos?", o: ["La potestad de modificar los cargos inicialmente aplicados por los agentes", "Apoyo en la correcta tipificacion de los delitos y adecuada aplicacion de los cargos, asegurando que se ajusten al marco legal y los hechos constatados", "La facultad de archivar investigaciones que no tengan suficiente base probatoria", "La elaboracion automatica de los informes policiales por parte del fiscal"], a: 1 },
      { q: "Que ocurre al acumular tres sanciones OOC de nivel 2?", o: ["Se aplica una suspension de 72 horas", "Se escala a sancion OOC nivel 3", "Se aplica directamente la expulsion", "Se revisa el caso por el Fiscal General"], a: 1 },
      { q: "Cual es el nivel minimo de cuenta requerido para ingresar a LSAG?", o: ["Nivel 3", "Nivel 10", "Nivel 6", "Nivel 8"], a: 2 },
      { q: "Que establece la Normativa respecto al desconocimiento de su contenido?", o: ["Exime al miembro de responsabilidad si no fue informado", "El desconocimiento no exime de su cumplimiento", "Solo aplica a miembros con mas de 3 meses en la faccion", "Permite una advertencia previa antes de sancionar"], a: 1 },
      { q: "Que ocurre con un fiscal observador en un procedimiento si ese caso llega a juicio?", o: ["Puede asumir la acusacion si el Fiscal General lo aprueba expresamente", "Queda inhabilitado para litigar o llevar la acusacion del mismo caso, debiendo ser asignado a otro fiscal", "Puede actuar como testigo experto pero no como fiscal acusador", "Debe recusar al juez si existe conflicto de intereses previo"], a: 1 },
      { q: "Que tipo de comunicacion es el simplex segun el Manual?", o: ["Una comunicacion prioritaria y bidireccional entre dos unidades", "Una comunicacion no prioritaria donde el transmisor emite un mensaje sin recibir feedback inmediato", "Un protocolo exclusivo para comunicaciones con el Centro de Comunicaciones", "Una comunicacion cifrada usada unicamente en operativos especiales"], a: 1 },
      { q: "Quien puede iniciar el tramite para incorporar a un testigo al programa de proteccion?", o: ["Cualquier agente policial actuante", "El Director del FIB o el USMS", "El Fiscal a cargo del caso", "El juez supremo de la Corte de Los Santos"], a: 2 },
      { q: "Cual es la funcion principal del Juez dentro de un juicio segun el Manual?", o: ["Presentar los cargos penales y revelar las pruebas al jurado", "Proteger los derechos del acusado y plantear objeciones", "Controlar el tribunal, decidir cuestiones de derecho, admitir o excluir evidencias y dictar sentencia", "Determinar los hechos a partir de las evidencias presentadas por ambas partes"], a: 2 },
      { q: "Que caracter tiene la orientacion brindada por el fiscal dentro del programa?", o: ["Vinculante y de obligado cumplimiento para las agencias policiales", "Jerarquico, con poder de supervision sobre las agencias", "No vinculante, y no debe interpretarse como una orden, instruccion operativa o imposicion de criterios", "Provisional, hasta que el Fiscal General ratifique las indicaciones"], a: 2 },
      { q: "Que puede solicitarse durante la fase de Audiencia Pre-Juicio y Mociones?", o: ["La incorporacion de nuevos testigos sin limite de tiempo", "La suspension indefinida del juicio por ambas partes", "La supresion de pruebas obtenidas de forma ilegal o testigos, a eleccion del juez", "La sustitucion del juez por uno de mayor rango"], a: 2 },
      { q: "Quien mantiene en todo momento la responsabilidad operativa y decisional sobre el procedimiento?", o: ["El fiscal del programa, en coordinacion con el Fiscal de Distrito", "El Fiscal General, como maxima autoridad institucional presente", "La IAA, como organo supervisor de las actuaciones", "Exclusivamente el personal policial actuante"], a: 3 },
      { q: "Cuando se debe contactar con el USSS segun el Manual?", o: ["Cuando se presencia un delito de drogas federal en la jurisdiccion", "Cuando un miembro esta bajo ataque y no recibamos respuesta del USMS y FIB, o ante delitos contra la moneda o contra cargos electos del gobierno", "Cuando se requiera escolta judicial para un testigo protegido", "Cuando un empleado necesite apoyo logistico en un allanamiento"], a: 1 },
      { q: "Que garantiza el principio 'Nullum crimen, nulla poena sine lege'?", o: ["Que nadie pueda ser detenido sin una causa legal justificada", "Que en caso de duda se falle siempre a favor del acusado", "Que una persona no pueda ser juzgada dos veces por el mismo hecho", "Que nadie sea condenado por una conducta que no este previamente definida como delito por una ley"], a: 3 },
      { q: "En la Normativa de TeamSpeak3, como deben identificarse los usuarios?", o: ["Con su apodo de juego y numero de placa", "Con su nombre de usuario del foro y faccion", "Con su nombre y apellido, mas un numero de identificacion unico siempre visible", "Solo con su numero de empleado interno"], a: 2 },
      { q: "Como se denomina la persona encargada de supervisar el personal en servicio desde el Centro de Comunicaciones?", o: ["Coordinador de Turno", "Despachador", "Supervisor de Enlace", "Controlador Fiscal"], a: 1 },
      { q: "Segun la Normativa OOC, como deben interpretar los miembros a sus personajes?", o: ["Libremente, sin restricciones de ningun tipo", "De acuerdo con sus biografias registradas en el foro, sin contradecir las reglas de GTAHUB ni la filosofia de LSAG", "Siguiendo unicamente las instrucciones del Fiscal General en cada sesion", "Basandose en las normas de roleplay de cualquier servidor de GTA V"], a: 1 }
    ]
  }
];
